version: "3.7"

services:
  app:
    container_name: cmp_backend
    image: cmp_backend
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./.env.prod
    depends_on:
      - db

  db:
    container_name: cmp_db
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file:
      - ./.env.prod.db

  worker:
    restart: unless-stopped
    container_name: cmp_worker
    build:
      context: .
      dockerfile: ./celery.Dockerfile
    command: celery -A cmp worker --loglevel=info
    env_file:
      - ./.env.prod
    depends_on:
      - rabbitmq
      - app

  rabbitmq:
    restart: unless-stopped
    image: rabbitmq:latest
    container_name: 'cmp_rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    env_file:
      - ./.env.prod.rabbitmq
