version: "3.7"

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: gunicorn cmp.wsgi:application --bind 0.0.0.0:8000 --workers 4 --threads 4
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file:
      - ./.env.prod.db

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - db